name: Cypress Tests - Saucedemo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      # Run Cypress tests using the official action
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          runTests: npm run cy:run
      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

