name: Cypress Tests - Saucedemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # Run Cypress tests (uses the npm script defined in package.json)
      - name: Run Cypress tests
        run: npm run cy:run

      # Generate Allure report after tests
      - name: Generate Allure report
        run: npm run allure:generate

      # Upload Allure report as GitHub Action artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

