name: Cypress Tests - Saucedemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Create required directories
        run: |
          mkdir -p screenshots
          mkdir -p allure-results
          mkdir -p allure-report

      - name: Run Cypress tests with Allure enabled
        run: |
          npx cypress run \
            --config video=false \
            --env allure=true

      - name: Generate Allure HTML Report
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-html
          path: allure-report/
          retention-days: 7